version: '3'

services:
  web:
    image: nginx:latest
    volumes: 
     - ./nginx:/etc/nginx
     - ./www:/var/www
    restart: always
    ports:
      - "80:80"
    networks:
      - registry

  registry:
    image: registry:2
    environment:
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: Registry
      REGISTRY_AUTH_HTPASSWD_PATH: /auth/registry.users
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /data
    volumes:
      - ./data:/data
      - ./registry/registry.users:/auth
    networks:
      - registry
networks:
  registry:
